apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-pvc
  namespace: teamcity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/teamcity"
